{
  "openapi": "3.0.3",
  "info": {
    "title": "Disputes",
    "description": "Occasionally, something goes wrong with a customer's order. To dispute a charge, a customer can create a dispute with PayPal. PayPal merchants, partners, and external developers can use the PayPal Disputes API to manage customer disputes.<blockquote><strong>Note:</strong> In the live environment, merchants cannot create disputes but can only respond to customer-created disputes. However, merchants can create disputes in the sandbox environment. When you create an app, enable [...]",
    "version": "1.11",
    "contact": {}
  },
  "servers": [
    {
      "url": "https://api-m.sandbox.paypal.com",
      "description": "PayPal Sandbox Environment"
    },
    {
      "url": "https://api-m.paypal.com",
      "description": "PayPal Live Environment"
    }
  ],
  "tags": [
    {
      "name": "disputes",
      "description": "Use the `/disputes` resource to list disputes, create disputes, show dispute details, and partially a dispute. Normally, an agent at PayPal creates disputes but now you can run test cases in the sandbox that create disputes."
    },
    {
      "name": "disputes-actions",
      "description": "Use the `/disputes` resource with a dispute ID and an action to:<ul><li>Accept a claim.</li><li>Accept an offer to resolve a dispute.</li><li>Acknowledge the return of an item related to a dispute.</li><li>Settle a dispute.</li><li>Appeal a dispute.</li><li>Cancel a dispute.</li><li>Change the reason for a dispute.</li><li>Deny an offer to resolve dispute.</li><li>Escalate a dispute to a claim.</li><li>Make an offer to resolve a dispute.</li><li>Make an offer to resolve a d[...]"
    },
    {
      "name": "referred-disputes",
      "description": "Use the `/customer/referred-disputes` resource to create a dispute for a referred case that was created by a partner or marketplace, show details for a referred dispute, by ID, notify referred refunds completed to PayPal, notify PayPal about referred dispute adjudication updates, and determine the dispute eligibility for referred disputes."
    },
    {
      "name": "validate-eligibility",
      "description": "Use the `/validate-eligibility/` resource to determine whether you can create a case for a transaction."
    },
    {
      "name": "compute-metrics",
      "description": "Use the `/compute-metrics` resource to provide metrics for all disputes."
    },
    {
      "name": "validate-referred-dispute-eligibility",
      "description": "Use the `/validate-referred-dispute-eligibility` resource to determine whether you can create a referred case for a transaction, by encrypted transaction ID."
    },
    {
      "name": "referred-disputes",
      "description": "Use the `/referred-disputes` resource to create a dispute for a referred case that was created by a partner or marketplace, show details for a referred dispute, by ID, notify referred refunds completed to PayPal, notify PayPal about referred dispute adjudication updates, and determine the dispute eligibility for referred disputes."
    },
    {
      "name": "referred-disputes-actions",
      "description": "Use the `/referred-disputes` resource with a dispute ID and an action to notify PayPal about adjudication updates for a referred dispute and notify PayPal about a refund for a referred dispute."
    },
    {
      "name": "partner-actions",
      "description": "Use the `/disputes/{id}/partner-actions/` resource to show dispute action details and partially update a dispute action."
    },
    {
      "name": "search-suggestions",
      "description": "Use the `/search-suggestions` resource to show search suggestions."
    },
    {
      "name": "dispute-events",
      "description": "Use the `/dispute-events` resource to send dispute events."
    },
    {
      "name": "refund-preference",
      "description": "Use the `/disputes/{id}/provide-refund-preference` resource to provide refund preferences for the dispute."
    },
    {
      "name": "return-compensation",
      "description": "Use the `/disputes/{id}/return-compensation` resource to return the compensation on the dispute provided by PayPal to the customer."
    }
  ],
  "paths": {
    "/v1/customer/disputes": {
      "get": {
        "summary": "List disputes",
        "description": "Lists disputes with a summary set of details, which shows the <code>dispute_id</code>, <code>reason</code>, <code>status</code>, <code>dispute_state</code>, <code>dispute_life_cycle_stage</code>, <code>dispute_channel</code>, <code>dispute_amount</code>, <code>create_time</code> and <code>update_time</code> fields.<br/><br/>To filter the disputes in the response, specify one or more optional query parameters. To limit the number of disputes in the response, specify the <c[...]",
        "operationId": "disputes.list",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-buyer"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-ebay"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-partner"]
          }
        ],
        "tags": ["disputes"]
      }
    },
    "/v1/customer/disputes/{id}": {
      "get": {
        "summary": "Show dispute details",
        "description": "Shows details for a dispute, by ID.<blockquote><strong>Note:</strong> The fields that appear in the response depend on the access. For example, if the merchant requests shows dispute details, the customer's email ID does not appear.</blockquote>",
        "operationId": "disputes.get",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-buyer"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-ebay"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/read-partner"]
          }
        ],
        "tags": ["disputes"]
      },
      "patch": {
        "summary": "Partially update dispute",
        "description": "Partially updates a dispute, by ID. Seller can update the `communication_detail` value or The partner can add the `partner action` information.",
        "operationId": "disputes.patch",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          }
        ],
        "tags": ["disputes"]
      }
    },
    "/v1/customer/disputes/{id}/provide-evidence": {
      "post": {
        "summary": "Provide evidence",
        "description": "Provides evidence for a dispute, by ID. A merchant can provide evidence for disputes with the <code>WAITING_FOR_SELLER_RESPONSE</code> status while customers can provide evidence for disputes with the <code>WAITING_FOR_BUYER_RESPONSE</code> status. Evidence can be a proof of delivery or proof of refund document or notes, which can include logs. A proof of delivery document includes a tracking number while a proof of refund document includes a refund ID. For other evidence[...]",
        "operationId": "disputes.provide-evidence",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          },
          {
            "Oauth2": [
              "https://uri.paypal.com/services/disputes/update-partner"
            ]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/appeal": {
      "post": {
        "summary": "Appeal dispute",
        "description": "Appeals a dispute, by ID. To appeal a dispute, use the <code>appeal</code> link in the <a href=\"/docs/api/reference/api-responses/#hateoas-links/\">HATEOAS links</a> from the show dispute details response. If this link does not appear, you cannot appeal the dispute. Submit new evidence as a document or notes in the JSON request body. For constraints and rules regarding documents, see <a href=\"/docs/integration/direct/customer-disputes/integration-guide/#documents\">docu[...]",
        "operationId": "disputes.appeal",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/accept-claim": {
      "post": {
        "summary": "Accept claim",
        "description": "Accepts liability for a claim, by ID. When you accept liability for a claim, the dispute closes in the customer’s favor and PayPal automatically refunds money to the customer from the merchant's account. Allowed accept_claim_type values for the request is available in dispute details <a href=\"/docs/api/customer-disputes/v1/#definition-allowed_response_options\">allowed response options</a> object.",
        "operationId": "disputes.accept-claim",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/adjudicate": {
      "post": {
        "summary": "Settle dispute",
        "description": "<blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Settles a dispute in either the customer's or merchant's favor. Merchants can make this call in the sandbox to complete end-to-end dispute resolution testing, which mimics the dispute resolution that PayPal agents normally complete. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>adjudicate</code> link  should be available in the <a href[...]",
        "operationId": "disputes.adjudicate",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/require-evidence": {
      "post": {
        "summary": "Update dispute status",
        "description": "<blockquote><strong>Important:</strong> This method is for sandbox use only.</blockquote> Updates the status of a dispute, by ID, from <code>UNDER_REVIEW</code> to either:<ul><li><code>WAITING_FOR_BUYER_RESPONSE</code></li><li><code>WAITING_FOR_SELLER_RESPONSE</code></li></ul>This status change enables either the customer or merchant to submit evidence for the dispute. To make this call, the dispute <code>status</code> must be <code>UNDER_REVIEW</code> and <code>require-e[...]",
        "operationId": "disputes.require-evidence",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/escalate": {
      "post": {
        "summary": "Escalate dispute to claim",
        "description": "Escalates the dispute, by ID, to a PayPal claim. To make this call, the stage in the dispute lifecycle must be `INQUIRY`.",
        "operationId": "disputes.escalate",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/send-message": {
      "post": {
        "summary": "Send message about dispute to other party",
        "description": "Sends a message about a dispute, by ID, to the other party in the dispute. Merchants and customers can only send messages if the `dispute_life_cycle_stage` value is `INQUIRY`. For constraints and rules regarding documents that can be attached as part of the message, see <a href=\"/docs/integration/direct/customer-disputes/integration-guide/#documents\">documents</a>. To send a message, use the <code>send-message</code> link in the <a href=\"/docs/api/reference/api-respons[...]",
        "operationId": "disputes.send-message",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/make-offer": {
      "post": {
        "summary": "Make offer to resolve dispute",
        "description": "Makes an offer to the other party to resolve a dispute, by ID. To make this call, the stage in the dispute lifecycle must be `INQUIRY`. If the customer accepts the offer, PayPal automatically makes a refund. Allowed offer_type values for the request is available in dispute details <a href=\"/docs/api/customer-disputes/v1/#definition-allowed_response_options\">allowed response options</a> object.",
        "operationId": "disputes.make-offer",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          },
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/accept-offer": {
      "post": {
        "summary": "Accept offer to resolve dispute",
        "description": "The customer accepts the offer from merchant to resolve a dispute, by ID. PayPal automatically refunds the amount proposed by merchant to the customer.",
        "operationId": "disputes.accept-offer",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/deny-offer": {
      "post": {
        "summary": "Deny offer to resolve dispute",
        "description": "Denies an offer that the merchant proposes for a dispute, by ID.",
        "operationId": "disputes.deny-offer",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-buyer"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/acknowledge-return-item": {
      "post": {
        "summary": "Acknowledge returned item",
        "description": "Acknowledges that the customer returned an item for a dispute, by ID. A merchant can make this request for disputes with the `MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED` reason. Allowed acknowledgement_type values for the request is available in dispute details <a href=\"/docs/api/customer-disputes/v1/#definition-allowed_response_options\">allowed response options</a> object. For constraints and rules regarding documents, see <a href=\"/docs/integration/direct/customer-dispu[...]",
        "operationId": "disputes.acknowledge-return-item",
        "security": [
          {
            "Oauth2": ["https://uri.paypal.com/services/disputes/update-seller"]
          }
        ],
        "tags": ["disputes-actions"]
      }
    },
    "/v1/customer/disputes/{id}/provide-supporting-info": {
      "post": {
        "summary": "Provide supporting information for dispute",
        "description": "Provides supporting information for a dispute, by ID. A merchant or buyer can make this request for disputes if they find the `provide-supporting-info` link in the HATEOAS links in the list disputes response. The party can provide the supporting information to PayPal to defend themselves only when the `dispute_life_cycle_stage` is `CHARGEBACK`, `PRE_ARBITRATION`, or `ARBITRATION`. They can provide a note that describes their part with details or upload any supporting docu[...]",
        "operationId": "disputes.provide-supporting-info",
        "security": [
          {
            "Oauth2": [
              "https://uri.paypal.com/services/disputes/update-seller",
              "https://uri.paypal.com/services/disputes/update-buyer",
              "https://uri.paypal.com/services/disputes/update-partner"
            ]
          }
        ],
        "tags": ["disputes-actions"]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "type": "oauth2",
        "description": "Oauth 2.0 authentication",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/v1/oauth2/token",
            "scopes": {
              "https://uri.paypal.com/services/disputes/read-seller": "This privilege allows client to read and search a disputes of a merchant but gets only a limited and allowed set of fields back .",
              "https://uri.paypal.com/services/disputes/read-buyer": "This privilege allows client to read and search disputes but returns a limited and allowed set of fields back.",
              "https://uri.paypal.com/services/disputes/read-ebay": "This privilege allows client to read and search a disputes of an user but gets only a limited and allowed set of fields back to ebay.",
              "https://uri.paypal.com/services/disputes/read": "This privilege allows client to read and search a dispute of an user with all fields.",
              "https://uri.paypal.com/services/disputes/webhooks": "This privilege allows webhook platform to read a dispute event",
              "https://uri.paypal.com/services/disputes/create": "This privilege allows client to validate eligibility and create a dispute on his transaction(s).",
              "https://uri.paypal.com/services/disputes/update-seller": "This privilege allows client to update a dispute (Merchant actions).",
              "https://uri.paypal.com/services/disputes/update-buyer": "This privilege allows client to update a dispute (customer actions).",
              "https://uri.paypal.com/services/referred-disputes/readwrite": "This privilege allows client to read and update a referred dispute.",
              "https://uri.paypal.com/services/disputes/read-partner": "This privilege allows client to read and search disputes but returns a limited and allowed set of fields back.",
              "https://uri.paypal.com/services/disputes/update-partner": "This privilege allows client to update a dispute (Partner actions)."
            }
          }
        }
      }
    }
  }
}
